stages:
  - test
  - build
  - package
  - deploy

cache:
  paths:
    - vendor
  untracked: true

services:
  - docker:dind


test:
  image: node:8.6.0
  stage: test
  before_script:
    - npm install -g ethereumjs-testrpc truffle
    - testrpc -l 0xFFFFFF &
  script:
    - truffle test --network ci


